### ISSUE TITLE
Bug related to topview Parameters

### ISSUE THREAD

**Issue by h0anle** [CEA-MetroCarac/fitspy#12]
**Steps to reproduce the bug:**

    - Load a fitted model which compose of some peak_models (JSON file)
    - Apply the loaded model to a spectrum.
    - Open "Parameter" and delete one or more 'peak_model'.
    - Back to the GUI and apply the 'loaded model' again to the spectrum -> BUG 
    
 ==> The parameters do not show the peak parameters correctly. This is because the length of the 'peak_models' and 'peak_labels' lists is now different.

**Comment by patquem** [comment]
Hi @h0anle,
This issue has been fixed in 2bd4e0a39fefc29ba11dbbe6983ef7b314c03382
